version: '3.9'

services:
  postgres:
    image: postgres
    volumes:
      - ./sql-scripts/tables-creation.sql:/docker-entrypoint-initdb.d/tables-creation.sql
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"
    networks:
      - backend

  gateway:
    container_name: gateway
    build:
      context: ./wex-transaction-gateway
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - backend

  transaction-service:
    container_name: transaction-service
    build:
      context: ./wex-transaction-transaction-service
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - postgres
    networks:
      - backend

networks:
  backend:
    name: backend
    driver: bridge